--- #YAML:1.0
name:               Dancer-Plugin-DebugToolbar
version:            0.015
abstract:           A debugging toolbar for Dancer web applications
author:
    - Michal Wojciechowski <odyniec@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    File::ShareDir::Install:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Dancer:               1.307
    File::ShareDir:       1
    File::ShareDir::Install:  0
    Test::More:           0
    Tie::Hash::Indexed:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
